/**
 * Pro-grade printable Quote / Estimate / Invoice for Black Timber Contracting.
 *
 * This is NOT generated by OpenRouter — AI fills the admin form; this component
 * renders the customer-facing PDF via Print (Ctrl+P → Save as PDF).
 *
 * Brand: logo + #c5a880 gold + #0b0a09 charcoal (see src/lib/brand.ts).
 */

import Image from "next/image";
import { BRAND } from "@/lib/brand";
import type { BusinessProfile } from "@/lib/business-config";
import type {
  AdminDocumentType,
  AdminQuoteSaved,
  AdminQuoteTaxMode,
} from "@/lib/admin/schemas";

export function idToDocType(id: string): AdminDocumentType {
  const prefix = id.charAt(0).toUpperCase();
  if (prefix === "I") return "invoice";
  if (prefix === "E") return "estimate";
  return "quote";
}

const TAX_MODE_LABEL: Record<AdminQuoteTaxMode, string> = {
  real_property_install: "Installed into real property",
  supply_only: "Supply only",
  mixed_split: "Mixed (split contract)",
  exempt: "PST exempt",
};

const SOURCE_LABEL: Record<string, string> = {
  fernie_hh_stocked: "Fernie HH (stocked)",
  fernie_hh_special_order: "Fernie HH (special order)",
  other_supplier: "Other supplier",
  labor: "Labor",
  subcontractor: "Subcontractor",
  other: "—",
};

function fmtCAD(n: number): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(n);
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

interface DocCopy {
  headline: string;
  dateLabel: string;
  footerNote: string;
  showSignature: boolean;
  showPayment: boolean;
}

function copyForDoc(docType: AdminDocumentType): DocCopy {
  switch (docType) {
    case "invoice":
      return {
        headline: "Invoice",
        dateLabel: "Payment due",
        footerNote:
          "Thank you for your business. Please remit payment by the due date above. Disputed items must be raised in writing within 7 days of receipt.",
        showSignature: false,
        showPayment: true,
      };
    case "estimate":
      return {
        headline: "Estimate",
        dateLabel: "Good until",
        footerNote:
          "Budgetary estimate based on scope as understood. Final pricing follows a site visit and a formal Quote. Material costs reflect Fernie HH PRO ballparks and desk confirmation.",
        showSignature: false,
        showPayment: false,
      };
    default:
      return {
        headline: "Quote",
        dateLabel: "Valid until",
        footerNote:
          "Valid until the date above. Pricing based on Fernie HH PRO ballparks at issue; desk confirmation required. Final price requires an in-person site visit. Hidden conditions may revise affected lines.",
        showSignature: true,
        showPayment: false,
      };
  }
}

function statusLabel(status: string, docType: AdminDocumentType): string {
  if (docType === "invoice") {
    if (status === "sent") return "Issued";
    if (status === "paid") return "Paid";
  }
  return status;
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="text-[10px] font-mono uppercase tracking-[0.35em] mb-2"
      style={{ color: BRAND.goldDark }}
    >
      {children}
    </h2>
  );
}

export default function BrandedDocument({
  quote,
  business,
}: {
  quote: AdminQuoteSaved;
  business: BusinessProfile;
}) {
  const docType = quote.documentType ?? idToDocType(quote.id);
  const copy = copyForDoc(docType);

  return (
    <article className="btc-document relative bg-white text-[#1a1816] mx-auto shadow-2xl shadow-black/50 print:shadow-none print:rounded-none rounded-lg overflow-hidden">
      {/* ── Branded header band ── */}
      <header
        className="relative px-10 pt-8 pb-7 print:px-10"
        style={{ background: BRAND.black }}
      >
        <div
          className="absolute top-0 left-0 right-0 h-1"
          style={{ background: `linear-gradient(90deg, ${BRAND.goldDark}, ${BRAND.gold}, ${BRAND.goldDark})` }}
        />
        <div className="flex items-start justify-between gap-6">
          <div className="flex items-center gap-5">
            <div className="relative w-[72px] h-[72px] shrink-0 rounded-md overflow-hidden bg-white/5 p-1.5">
              <Image
                src="/black-timber-logo.png"
                alt={`${business.name} logo`}
                fill
                sizes="72px"
                style={{ objectFit: "contain" }}
                priority
              />
            </div>
            <div>
              <p
                className="text-[10px] font-mono uppercase tracking-[0.45em] mb-1"
                style={{ color: BRAND.gold }}
              >
                {business.region}
              </p>
              <h1
                className="text-[26px] font-extrabold tracking-tight leading-none text-white"
              >
                {business.name}
              </h1>
              <p className="text-[11px] mt-2 text-white/75">
                {business.phone} · {business.email}
              </p>
              <p className="text-[11px] text-white/60">{business.domain}</p>
              {business.gstNumber ? (
                <p className="text-[10px] font-mono mt-1.5 text-white/50">
                  GST# {business.gstNumber}
                  {business.wcbNumber ? ` · WCB ${business.wcbNumber}` : ""}
                </p>
              ) : null}
            </div>
          </div>
          <div className="text-right shrink-0">
            <p
              className="text-[32px] font-extrabold uppercase tracking-tight leading-none"
              style={{ color: BRAND.gold }}
            >
              {copy.headline}
            </p>
            <p className="font-mono text-[13px] text-white/90 mt-2">{quote.id}</p>
            <dl className="mt-4 text-[11px] grid grid-cols-[auto_auto] gap-x-3 gap-y-1 justify-end text-white/80">
              <dt className="text-white/50 text-right">Issued</dt>
              <dd className="font-mono text-right text-white">{fmtDate(quote.updatedAt)}</dd>
              <dt className="text-white/50 text-right">{copy.dateLabel}</dt>
              <dd className="font-mono text-right text-white">{fmtDate(quote.validUntil)}</dd>
            </dl>
            <span
              className="inline-block mt-3 px-2.5 py-1 rounded text-[9px] font-mono uppercase tracking-widest"
              style={{
                background: `${BRAND.gold}22`,
                color: BRAND.gold,
                border: `1px solid ${BRAND.gold}66`,
              }}
            >
              {statusLabel(quote.status, docType)}
            </span>
          </div>
        </div>
      </header>

      {/* ── Body ── */}
      <div className="px-10 py-9 print:px-10">
        <section className="grid grid-cols-1 sm:grid-cols-2 gap-8">
          <div
            className="rounded-lg p-4"
            style={{ background: BRAND.paper, border: `1px solid ${BRAND.gold}33` }}
          >
            <SectionLabel>Bill to</SectionLabel>
            <p className="text-sm font-bold">{quote.customer.name}</p>
            {quote.customer.billingAddress ? (
              <p className="text-sm text-black/80 mt-1 whitespace-pre-line">
                {quote.customer.billingAddress}
              </p>
            ) : null}
            <div className="text-[12px] text-black/65 mt-2 space-y-0.5">
              {quote.customer.email ? <p>{quote.customer.email}</p> : null}
              {quote.customer.phone ? <p>{quote.customer.phone}</p> : null}
            </div>
          </div>
          <div
            className="rounded-lg p-4"
            style={{ background: BRAND.paper, border: `1px solid ${BRAND.gold}33` }}
          >
            <SectionLabel>Job site</SectionLabel>
            {quote.customer.jobSiteAddress ? (
              <p className="text-sm whitespace-pre-line">{quote.customer.jobSiteAddress}</p>
            ) : (
              <p className="text-sm text-black/50 italic">Same as billing</p>
            )}
          </div>
        </section>

        <section className="mt-7 break-inside-avoid">
          <SectionLabel>Project</SectionLabel>
          <p className="font-mono text-[11px] uppercase tracking-widest text-black/55">
            {quote.project.type.replace(/_/g, " ")}
            {quote.project.lengthFt && quote.project.widthFt
              ? ` · ${quote.project.lengthFt}ft × ${quote.project.widthFt}ft`
              : ""}
            {quote.project.material ? ` · ${quote.project.material}` : ""}
          </p>
          <p className="text-sm leading-relaxed mt-2">{quote.project.scopeSummary}</p>
        </section>

        <section className="mt-8">
          <table className="w-full text-[12.5px] border-collapse overflow-hidden rounded-lg">
            <thead>
              <tr style={{ background: BRAND.black }}>
                <th
                  className="text-left font-mono text-[9px] uppercase tracking-widest py-3 pl-3 pr-2 w-8"
                  style={{ color: BRAND.gold }}
                >
                  #
                </th>
                <th
                  className="text-left font-mono text-[9px] uppercase tracking-widest py-3 px-2"
                  style={{ color: BRAND.gold }}
                >
                  Description
                </th>
                <th
                  className="text-right font-mono text-[9px] uppercase tracking-widest py-3 px-2 w-14"
                  style={{ color: BRAND.gold }}
                >
                  Qty
                </th>
                <th
                  className="text-left font-mono text-[9px] uppercase tracking-widest py-3 px-2 w-12"
                  style={{ color: BRAND.gold }}
                >
                  UOM
                </th>
                <th
                  className="text-right font-mono text-[9px] uppercase tracking-widest py-3 px-2 w-24"
                  style={{ color: BRAND.gold }}
                >
                  Unit
                </th>
                <th
                  className="text-right font-mono text-[9px] uppercase tracking-widest py-3 pl-2 pr-3 w-28"
                  style={{ color: BRAND.gold }}
                >
                  Total
                </th>
              </tr>
            </thead>
            <tbody>
              {quote.lines.map((l, idx) => {
                const lineTotal = l.quantity * l.unitPriceCAD;
                return (
                  <tr
                    key={l.id}
                    className="border-b align-top"
                    style={{
                      borderColor: `${BRAND.gold}22`,
                      background: idx % 2 === 1 ? BRAND.paper : "#fff",
                    }}
                  >
                    <td className="py-2.5 pl-3 font-mono text-[11px] text-black/45">{idx + 1}</td>
                    <td className="py-2.5 px-2">
                      <div className="text-sm font-medium">{l.description}</div>
                      <div className="text-[10px] text-black/50 font-mono mt-0.5">
                        {SOURCE_LABEL[l.source] ?? "—"}
                      </div>
                    </td>
                    <td className="py-2.5 px-2 text-right font-mono">{l.quantity}</td>
                    <td className="py-2.5 px-2 font-mono text-black/60">{l.uom}</td>
                    <td className="py-2.5 px-2 text-right font-mono">{fmtCAD(l.unitPriceCAD)}</td>
                    <td className="py-2.5 pr-3 text-right font-mono font-semibold">
                      {fmtCAD(lineTotal)}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>

        <section className="mt-8 grid grid-cols-1 sm:grid-cols-[1fr_280px] gap-8 break-inside-avoid">
          <div className="text-[11.5px] leading-relaxed text-black/75 space-y-4">
            <div>
              <SectionLabel>Tax</SectionLabel>
              <p>{TAX_MODE_LABEL[quote.taxMode]}</p>
            </div>
            <div>
              <SectionLabel>Lead time</SectionLabel>
              <p>
                {quote.totals.maxLeadTimeDays > 0
                  ? `Up to ${quote.totals.maxLeadTimeDays} business days on special-order lines.`
                  : "Typically stocked or crew-scheduled; no special-order lead times anticipated."}
              </p>
            </div>
          </div>
          <div
            className="rounded-lg p-5 font-mono text-[12.5px]"
            style={{
              background: BRAND.paperAccent,
              border: `2px solid ${BRAND.gold}`,
            }}
          >
            <dl className="grid grid-cols-[1fr_auto] gap-y-1.5">
              <dt className="text-black/60">Subtotal</dt>
              <dd>{fmtCAD(quote.totals.subtotalCAD)}</dd>
              <dt className="text-black/60">Freight</dt>
              <dd>{fmtCAD(quote.totals.freightCAD)}</dd>
              <dt className="text-black/60">GST 5%</dt>
              <dd>{fmtCAD(quote.totals.gstCAD)}</dd>
              {quote.totals.pstCAD > 0 ? (
                <>
                  <dt className="text-black/60">PST 7%</dt>
                  <dd>{fmtCAD(quote.totals.pstCAD)}</dd>
                </>
              ) : null}
              <dt
                className="pt-3 mt-1 border-t text-[11px] uppercase tracking-widest font-bold"
                style={{ borderColor: BRAND.gold, color: BRAND.black }}
              >
                Total CAD
              </dt>
              <dd
                className="pt-3 mt-1 border-t text-right text-lg font-bold"
                style={{ borderColor: BRAND.gold, color: BRAND.black }}
              >
                {fmtCAD(quote.totals.grandTotalCAD)}
              </dd>
            </dl>
          </div>
        </section>

        {copy.showPayment ? (
          <section
            className="mt-8 grid sm:grid-cols-2 gap-6 p-5 rounded-lg break-inside-avoid"
            style={{ background: BRAND.paperAccent, border: `1px solid ${BRAND.gold}55` }}
          >
            <div>
              <SectionLabel>Payment terms</SectionLabel>
              <p className="text-sm font-semibold">{quote.paymentTerms?.trim() || "Net 14"}</p>
              <p className="text-[11px] text-black/60 mt-1">Due {fmtDate(quote.validUntil)}</p>
            </div>
            <div>
              <SectionLabel>How to pay</SectionLabel>
              <p className="text-[12px] leading-relaxed whitespace-pre-line">
                {quote.paymentInstructions?.trim() ||
                  [
                    business.eTransferEmail
                      ? `E-transfer: ${business.eTransferEmail}`
                      : null,
                    `Cheques payable to ${business.legalName}`,
                  ]
                    .filter(Boolean)
                    .join("\n")}
              </p>
            </div>
          </section>
        ) : null}

        {copy.showSignature ? (
          <section className="mt-10 grid sm:grid-cols-2 gap-10 break-inside-avoid">
            {["Accepted by (customer)", "Black Timber Contracting"].map((title) => (
              <div key={title}>
                <SectionLabel>{title}</SectionLabel>
                {["Signature", "Print name", "Date"].map((label) => (
                  <div
                    key={label}
                    className="border-t mt-8 pt-1"
                    style={{ borderColor: `${BRAND.gold}88` }}
                  >
                    <p className="text-[10px] text-black/50">{label}</p>
                  </div>
                ))}
              </div>
            ))}
          </section>
        ) : null}
      </div>

      <footer
        className="px-10 py-5 text-[11px] leading-relaxed text-white/75"
        style={{ background: BRAND.charcoal, borderTop: `3px solid ${BRAND.gold}` }}
      >
        <p>{copy.footerNote}</p>
        <p className="mt-2 font-mono text-[10px] text-white/45">
          {copy.headline} {quote.id} · {business.legalName}
        </p>
      </footer>
    </article>
  );
}
